extends:
  - airbnb
  - airbnb/hooks
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parserOptions:
  ecmaVersion: 2020
  sourceType: module
